POST http://localhost:5000/register
Content-Type: application/json

{
    "email": "test1@gmail.com",
    "firstName" : "test1",
    "lastName" : "test1",
    "affiliation": 3,
    "password": "Pass&123"
}

###`

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "test1@gmail.com",
    "password": "Pass&123"
}

###

GET http://localhost:5000/match/find
Content-Type: application/json

{
    "userId": "6030bd7c572de23214f8b707",
    "issue": "Gun Control",
    "rating": null
}