POST http://localhost:5000/register
Content-Type: application/json

{
    "email": "test1@gmail.com",
    "first_name" : "test1",
    "last_name" : "test1",
    "affiliation": 3,
    "password": "Pass&123"
}

###`

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "test1@gmail.com",
    "password": "Pass&123"
}